apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oxui
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-oxui@sha256:25f7f722588515e516d8e73c859cd83c107b04758dc33d78acd1f49fd08d7e34
        name: my-nodejs
        resources: {}
status: {}
